# Adapted from https://goreleaser.com/customization/ko/#example for using ko to
# release Docker images

before:
  hooks:
    - go mod tidy

# Build standalone binaries:
builds:
  - env:
      # We are distributing these as static binaries, so trying to avoid
      # dependencies on specific glibc versions etc.
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    binary: '{{ .ProjectName }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

# Build Docker images:
kos:
  - repository: userclouds/ucconfig
    base_image: hashicorp/terraform
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

release:
  # If you want to manually examine the release before its live, uncomment this line:
  # draft: true

changelog:
  skip: true
